### ISSUE TITLE
Use a dual X11-MIT and GPL2 license

### ISSUE THREAD

**Issue by philiptaron** [xyproto/tinyxxd#7]
The original `xxd` project includes this acknowledgement in its man page:

> AUTHOR
> > (c) 1990-1997 by Juergen Weigert
> > <jnweiger@informatik.uni-erlangen.de>
> >
> > Distribute freely and credit me,
> > make money and share with me,
> > lose money and don't ask me.
> >
> > Manual page started by Tony Nugent
> > <tony@sctnugen.ppp.gu.edu.au> <T.Nugent@sct.gu.edu.au>
> > Small changes by Bram Moolenaar.  Edited by Juergen Weigert.

Could the `tinyxxd` project include the appropriate acknowledgement about the original author(s), even if it's about their inspiration rather than their code as such?

**Comment by emilazy** [comment]
Just to add some colour about my specific licensing concerns here; the `xxd.c` in Vim contains this notice:

```
 * (c) 1990-1998 by Juergen Weigert (jnweiger@gmail.com)
 *
 * I hereby grant permission to distribute and use xxd
 * under X11-MIT or GPL-2.0 (at the user's choice).
 *
 * Contributions by Bram Moolenaar et al.
```

That needs to be retained somewhere, whether in the comments of `xxd.c` or the `README.md`.

Clarification on the exact licensing terms would be good too: the original is `MIT or GPL-2.0-only`; the `tinyxxd` repository says GPL2, but the Arch packaging says `GPL-2.0-or-later`. I think it can only be `GPL-2.0-only`, as the licence notice in the original `xxd.c` doesn’t permit relicensing to GPL 3+ and this repository doesn’t contain any wording about later versions. (Retaining the original `MIT or GPL-2.0-only` would only be possible with consent of the external contributors to `tinyxxd`, but it’s fine to drop one half of the dual licensing, so that’s not an issue for us.)

**Comment by xyproto** [comment]
Thanks for raising the issue. The Arch Linux package may very well be wrong, and that it should be GPL-2.0-only instead of GPL-2.0-or-later. I created an issue for the Arch Linux package here: https://gitlab.archlinux.org/archlinux/packaging/packages/tinyxxd/-/issues/1

Last time I went over the license text, I found that the code used by tinyxxd is only covered by GPL2, and not by any other license, but I'll double-check this. ViM is under multiple licenses.

**Comment by emilazy** [comment]
The header in the original file is pretty clearly `MIT OR GPL-2.0-only`. However, `MIT OR GPL-2.0-only` can be used as `GPL-2.0-only` while dropping the `MIT`, so it’s perfectly fine to fork it under `GPL-2.0-only`, as you’ve done. Since this repository declares GPL 2 and doesn’t include the MIT licence, the external contributions since the fork happened are licensed `GPL-2.0-only` (under the GitHub TOS and general presumption). So restoring `MIT OR GPL-2.0-only` would only be possible with the permission of those contributors.

There is a slight nuance here where it’s ambiguous whether the Vim licence applies to the changes in Vim’s version of the original. I’d tend to assume that any further contributions on the Vim end from other people are under the licence declared in the `xxd.c` file unless there’s anything in the Vim distribution that clearly signals that modifications to the code are under another licence. The closest thing is probably “It is not allowed to remove this license from the distribution of the Vim sources, parts of it or from a modified version”, but I don’t know if `xxd.c` would count as “parts of [the Vim sources]” given its separate origin and copyright and licensing notice. I also don’t know if this would carry over to `xxd.1`, which is in another part of the source tree and was written by another author.

Possibly you could seek out permission from the external contributors to relicense their changes under `(GPL-2.0-only OR MIT) AND Vim`, but… eh, I’d tend to assume that you can just stick with the original licence. The only licensing notice in the man page is very permissive anyway. Since it doesn’t seem to really matter whether this project is copyleft or not, the best way forward might be to just clarify in this repository that it’s GPL version 2.0 only, include the copyright notice from the original author and the further contributions notice, and update the Arch package’s licence to match.

(Sorry, I’ve dealt with too many licensing issues in our distribution lately so my pedantry has become quite finely‐honed 😅)

**Comment by emilazy** [comment]
I forgot to mention one additional nuance: putting aside the Vim licence question for now, the main downside of `GPL-2.0-only` that I can see, compared to restoring `MIT OR GPL-2.0-only` with the permission of the small handful of contributors since the fork, is that it would not be possible for Vim to fold any changes made here back into its `xxd.c` without dropping the more permissive licence from its code (which they could do, but may not want to). Aligning the licences would therefore potentially be of benefit to the Vim upstream. However it’s of course the prerogative of you and the other `tinyxxd` contributors whether you want that to be possible.

**Comment by xyproto** [comment]
I am in favor of having both, I just need to look into this properly. 👍🙂

**Comment by xyproto** [comment]
The `xxd.c` source code has this comment:

https://github.com/vim/vim/blob/master/src/xxd/xxd.c#L67

```
 * (c) 1990-1998 by Juergen Weigert (jnweiger@gmail.com)
 *
 * I hereby grant permission to distribute and use xxd
 * under X11-MIT or GPL-2.0 (at the user's choice).
 *
 * Contributions by Bram Moolenaar et al.
```

This gives permission to select either X11-MIT or GPL2.

When I forked `xxd` to `tinyxxd`, I selected GPL2 (which I assume is `GPL-2.0-only` and not `GPL-2.0-or-later`. It's not specified explicitly if `GPL-2.0-or-later` would also be fine).

I like the idea of offering `tinyxxd` as a single, well known and understood license, with no additional requirements of comments in source code or additional text files.

As I see it, acknowledging all previous contributors to `xxd` and `tinyxxd` is not needed, since this is not required by GPL2.

Dual licensing under X11-MIT could be a "nice to have", as well as adding a `CONTRIBUTORS.md` file that list all previous contributors.

I can ask ViM upstream if `GPL-2.0-or-later` instead of `GPL-2.0-only` for a fork of `xxd` would be fine.

Are there cases where the `X11-MIT` license would be useful? The Linux kernel is also GPL2 licensed, so in connection with Linux distros, licensing it under GPL2 should be fine. Are there use cases where it would not be fine?

**Comment by xyproto** [comment]
@oliverkwebb @Ordoviz Would you mind if `tinyxxd` was not only licensed under GPL2, but dual licensed under GPL2 + X11-MIT, just like `xxd` from ViM is?

**Comment by xyproto** [comment]
I added `CONTRIBUTORS.md` ✅ 

Now only the dual licensing topic should be left, for this issue.

**Comment by Ordoviz** [comment]
I agree to dual-license my contributions under `MIT OR GPL-2.0-only`.

**Comment by oliverkwebb** [comment]
> @oliverkwebb @Ordoviz Would you mind if `tinyxxd` was not only licensed under GPL2, but dual licensed under GPL2 + X11-MIT, just like `xxd` from ViM is?

You are free to re-license any contributions of mine to any of your projects to any open-source license (I.e. Yeah, putting the code under a dual MIT-GPLv2 license is fine by me)

**Comment by xyproto** [comment]
tinyxxd is now dual licensed under GPL-2.0-only and MIT.
